Repository LibreELEC/LibreELEC.tv, pull requests merged in 2018-05, with the labels that each got.

#2654 kodi: Early May 2018
  packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.dvbviewer/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.pictureit/package.mk
  packages/mediacenter/kodi/package.mk
  packages/multimedia/ffmpeg/package.mk
  packages/multimedia/ffmpeg/patches/ffmpeg-99.0001-backport-rkmppdec-fixes.patch
  packages/multimedia/ffmpeg/patches/ffmpeg-99.1003-pfcd_hevc_optimisations.patch
  packages/multimedia/ffmpeg/patches/ffmpeg-99.1004-added_upstream_mvc_patches.patch
Labels: LE 9.0, PACKAGE, UPDATE

#1776 Don't cause system to hang on halt/reboot when net-booting
  packages/network/connman/package.mk
  packages/network/connman/patches/connman-01-build-add-disable-stats-option.patch
  packages/sysutils/busybox/scripts/init
Labels: BUGFIX, FEATURE, LE 9.0

#2678 mesa: update to mesa-18.0.2
  packages/graphics/mesa/package.mk
Labels: LE 9.0, PACKAGE, UPDATE

#2623 RPi, Generic: backport proposed patch to reduce IR latency
  packages/linux/patches/default/linux-999-improve-ir-timeout-handling.patch
  packages/linux/patches/raspberrypi/linux-999-improve-ir-timeout-handling.patch
Labels: IMPROVEMENT, KERNEL, LE 9.0

#2688 adafruit-libraries: update of various modules [master]
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_DHT/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_GPIO/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_LED_Backpack/package.mk
  packages/addons/libraries/adafruit-libraries/changelog.txt
  packages/addons/libraries/adafruit-libraries/package.mk
Labels: ADDONS, BACKPORT DONE, LE 9.0, UPDATE

#2687 adafruit-libraries: update of various modules [8.2]
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_ADS1x15/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_ADXL345/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_BMP/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_CharLCD/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_DHT/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_GPIO/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_LED_Backpack/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_LSM303/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_MCP3008/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_MCP4725/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_PCA9685/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_PureIO/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_SI1145/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_TCS34725/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_VCNL40xx/package.mk
  packages/addons/addon-depends/adafruit-libraries-depends/Adafruit_Python_WS2801/package.mk
  packages/addons/libraries/adafruit-libraries/changelog.txt
  packages/addons/libraries/adafruit-libraries/package.mk
Labels: ADDONS, LE 8.2, UPDATE

#2691 config: set version to devel
  config/version
Labels: LE 8.2, UPDATE

#2693 create_addon: jenkins specific quirks
  scripts/create_addon
Labels: ADDONS, BUILDSYSTEM, LE 9.0

#2681 Make: Fix building on arch linux
  packages/devel/make/patches/make-do-not-assume-glob-internals.patch
  packages/devel/make/patches/support-glob-interface-v2.patch
Labels: BUGFIX, BUILDSYSTEM, LE 9.0, PACKAGE

#2686 meson: update to 0.46.0
  packages/python/devel/meson/package.mk
  packages/python/devel/meson/patches/meson-0001-Support-data-types-larger-than-128-bytes.patch
Labels: LE 9.0, UPDATE

#2677 qemu: update to 2.12.0
  packages/tools/qemu/package.mk
Labels: LE 9.0, UPDATE

#2698 connman: update to connman-1.36
  packages/network/connman/package.mk
  packages/network/connman/patches/connman-01-build-add-disable-stats-option.patch
  packages/network/connman/patches/connman-06-ntp-startup.patch
Labels: LE 9.0, PACKAGE, UPDATE

#2675 vdr-addon: update to 2.4.0
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-ddci2/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-dummydevice/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-dvbapi/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-eepg/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-epgfixer/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-epgfixer/patches/vdr-plugin-epgfixer-02-VDR-2.3.x-fix.patch
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-epgsearch/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-iptv/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-live/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-restfulapi/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-robotv/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-satip/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-streamdev/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-streamdev/patches/vdr-plugin-streamdev-02_2.3.9_lock_fix.patch
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-vnsiserver/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscan/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-wirbelscancontrol/package.mk
  packages/addons/addon-depends/vdr-plugins/vdr-plugin-xmltv2vdr/package.mk
  packages/addons/addon-depends/vdr/package.mk
  packages/addons/addon-depends/vdr/patches/vdr-10-upstream-fix-svdrp-modt-recflag.diff
  packages/addons/service/vdr-addon/changelog.txt
  packages/addons/service/vdr-addon/package.mk
Labels: ADDONS, LE 9.0, UPDATE

#2665 oscam: update to 11420
  packages/addons/service/oscam/changelog.txt
  packages/addons/service/oscam/package.mk
  packages/addons/service/oscam/patches/oscam-01-revision.patch
  packages/addons/service/oscam/source/bin/oscam.start
  packages/addons/service/oscam/source/default.py
  packages/addons/service/oscam/source/oscam-default.conf
  packages/addons/service/oscam/source/resources/language/English/strings.po
  packages/addons/service/oscam/source/resources/language/English/strings.xml
  packages/addons/service/oscam/source/resources/settings.xml
  packages/addons/service/oscam/source/settings-default.xml
Labels: ADDONS, LE 9.0, UPDATE

#2699 oscam: add missing openssl dependency
  packages/addons/service/oscam/package.mk
Labels: ADDONS, BUGFIX, LE 9.0

#2701 pngquant: update to 2.11.7
  packages/addons/addon-depends/pngquant/package.mk
  packages/addons/addon-depends/pngquant/patches/pngquant-no-temp-dir.patch
Labels: BUGFIX, LE 9.0, UPDATE

#2702 strace: fix url
  packages/addons/addon-depends/system-tools-depends/strace/package.mk
Labels: ADDONS, BUGFIX, LE 9.0

#2705 samba: update to samba-4.8.2
  packages/network/samba/package.mk
Labels: LE 9.0, PACKAGE, UPDATE

#2703 systemd: add patches to fix 3.14 aml
  packages/sysutils/systemd/patches/systemd-0100-fix-glibc-2.27-build.patch
  packages/sysutils/systemd/patches/systemd-0201-fix-segfaults-in-libc-after-mounting-cgroup.patch
  packages/sysutils/systemd/patches/systemd-0202-fix-_nr_statx-buildspam-aml.patch
Labels: BUGFIX, LE 9.0

#2704 xf86-video-nvidia: update to xf86-video-nvidia-390.59
  packages/x11/driver/xf86-video-nvidia/package.mk
  packages/x11/driver/xf86-video-nvidia/udev.d/96-nvidia.rules
Labels: HARDWARE, LE 9.0, PACKAGE, UPDATE

#2685 buildsystem: use no-lto, when lto is disabled
  config/functions
  config/optimize
  packages/mediacenter/kodi/package.mk
Labels: BUGFIX, BUILDSYSTEM, LE 9.0

#2692 RPi, Generic: fix erratic IR timeout behaviour on Topseed mceusb receiver 1784:0011
  packages/linux/patches/default/linux-999-improve-ir-timeout-handling.patch
  packages/linux/patches/raspberrypi/linux-999-improve-ir-timeout-handling.patch
Labels: BUGFIX, LE 9.0, MERGE ¯\_(ツ)_/¯ 💥

#2694 Generic: allow lower IR timeouts on ITE CIR devices
  packages/linux/patches/default/linux-999-improve-ir-timeout-handling-of-ite-cir.patch
Labels: IMPROVEMENT, LE 9.0, MERGE ¯\_(ツ)_/¯ 💥

#2712 addon/librespot: Update to 431be
  packages/addons/service/librespot/changelog.txt
  packages/addons/service/librespot/package.mk
  packages/addons/service/librespot/patches/librespot-02_kodi_hooks.patch
  packages/addons/service/librespot/patches/librespot-03_pulseaudio_sink.patch
  packages/addons/service/librespot/patches/librespot-04_add_kSupportsPlaylistV2_enum.patch
  packages/addons/service/librespot/source/bin/librespot.onevent
  packages/addons/service/librespot/source/bin/librespot.onstart
  packages/addons/service/librespot/source/bin/librespot.onstop
  packages/addons/service/librespot/source/bin/librespot.start
  packages/addons/service/librespot/source/default.py
  packages/addons/service/librespot/source/resources/language/English/strings.po
  packages/addons/service/librespot/source/resources/settings.xml
  packages/addons/service/librespot/source/settings-default.xml
Labels: ADDONS, LE 9.0, UPDATE

#2713 librespot: backport of #2712
  packages/addons/service/librespot/changelog.txt
  packages/addons/service/librespot/package.mk
  packages/addons/service/librespot/patches/librespot-02_kodi_hooks.patch
  packages/addons/service/librespot/patches/librespot-03_pulseaudio_sink.patch
  packages/addons/service/librespot/patches/librespot-04_add_kSupportsPlaylistV2_enum.patch
  packages/addons/service/librespot/source/bin/librespot.onevent
  packages/addons/service/librespot/source/bin/librespot.onstart
  packages/addons/service/librespot/source/bin/librespot.onstop
  packages/addons/service/librespot/source/bin/librespot.start
  packages/addons/service/librespot/source/default.py
  packages/addons/service/librespot/source/resources/language/English/strings.po
  packages/addons/service/librespot/source/resources/settings.xml
  packages/addons/service/librespot/source/settings-default.xml
Labels: ADDONS, LE 8.2, UPDATE

#2709 rust: rework
  packages/addons/addon-depends/librespot-depends/rust/package.mk
  packages/addons/addon-depends/librespot-depends/rustup.rs/package.mk
Labels: ADDONS, BUGFIX, LE 9.0, UPDATE

#2710 rust: backport of #2709
  packages/addons/addon-depends/librespot-depends/rust/package.mk
  packages/addons/addon-depends/librespot-depends/rustup.rs/package.mk
Labels: ADDONS, BUGFIX, LE 8.2, UPDATE

#2719 rustup.rs: use wget if curl is unavailable
  packages/addons/addon-depends/librespot-depends/rustup.rs/patches/rustup.rs-01_wget.patch
Labels: BUGFIX, LE 9.0

#2720 rustup.rs: backport of #2719
  packages/addons/addon-depends/librespot-depends/rustup.rs/patches/rustup.rs-01_wget.patch
Labels: BUGFIX, LE 8.2

#2689 init: add sky42 enhancements/bug fixes
  config/options
  packages/devel/glibc/package.mk
  packages/sysutils/busybox/scripts/getedid
  packages/sysutils/busybox/scripts/init
  packages/tools/installer/config/installer.conf
  packages/tools/installer/package.mk
  packages/tools/installer/scripts/installer
  packages/tools/syslinux/package.mk
  projects/RPi/devices/RPi/linux/linux.arm.conf
  projects/RPi/devices/RPi2/linux/linux.arm.conf
  projects/Rockchip/devices/MiQi/linux/rockchip-4.4/linux.arm.conf
  projects/Rockchip/devices/RK3328/linux/rockchip-4.4/linux.aarch64.conf
  projects/Rockchip/devices/RK3399/linux/rockchip-4.4/linux.aarch64.conf
  projects/Rockchip/devices/TinkerBoard/linux/rockchip-4.4/linux.arm.conf
  scripts/image
  scripts/mkimage
Labels: BUGFIX, LE 9.0

#2714 Xorg package bumps
  packages/x11/app/xkbcomp/package.mk
  packages/x11/data/xkeyboard-config/package.mk
  packages/x11/driver/xf86-video-amdgpu/package.mk
  packages/x11/driver/xf86-video-ati/package.mk
  packages/x11/lib/libXfont2/package.mk
  packages/x11/lib/libxcb/package.mk
  packages/x11/lib/libxshmfence/package.mk
  packages/x11/lib/libxshmfence/patches/libxshmfence-01-fix-glibc-2.27.patch
  packages/x11/proto/xcb-proto/package.mk
  packages/x11/util/util-macros/package.mk
Labels: LE 9.0, UPDATE

#2682 linux: update to 4.14.43
  packages/graphics/bcm2835-driver/package.mk
  packages/linux-firmware/intel-ucode/package.mk
  packages/linux-firmware/iwlwifi-firmware/package.mk
  packages/linux-firmware/kernel-firmware/package.mk
  packages/linux/package.mk
  packages/tools/bcm2835-bootloader/package.mk
Labels: LE 9.0, PACKAGE, UPDATE

#2715 multimedia-tools: add-on update
  packages/addons/addon-depends/faad2/package.mk
  packages/addons/addon-depends/faad2/patches/faad2-2.7-automake_1.13.patch
  packages/addons/addon-depends/faad2/patches/faad2-2.7-mp4ff_shared.patch
  packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/depends/libzen/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/tstools/package.mk
  packages/addons/tools/multimedia-tools/changelog.txt
  packages/addons/tools/multimedia-tools/package.mk
  packages/audio/alsa-lib/package.mk
  packages/audio/alsa-lib/patches/alsa-lib-USB_Soundblaster_HD.patch
  packages/audio/alsa-lib/patches/alsa-lib-asound.conf_configdir.patch
  packages/audio/alsa-utils/package.mk
  packages/audio/libogg/package.mk
  packages/audio/libvorbis/package.mk
  packages/audio/libvorbis/patches/libvorbis-1.3.3-configure.patch
  packages/audio/pulseaudio/package.mk
  packages/audio/soxr/package.mk
Labels: ADDONS, LE 9.0, UPDATE

#2669 minor cleanup
  packages/lang/gcc-linaro-aarch64-elf/package.mk
  packages/lang/gcc-linaro-arm-eabi/package.mk
  packages/virtual/libc/package.mk
Labels: CLEANUP, LE 9.0

#2723 tools/docker: add bionic and stretch containers
  tools/docker/README.md
  tools/docker/bionic/Dockerfile
  tools/docker/stretch/Dockerfile
  tools/docker/xenial/Dockerfile
Labels: BUILDSYSTEM, IMPROVEMENT

#2662 tvheadend42: update to 4.2.6
  packages/addons/service/tvheadend42/changelog.txt
  packages/addons/service/tvheadend42/package.mk
  packages/addons/service/tvheadend42/patches/tvheadend42-01_makefile.patch
  packages/addons/service/tvheadend42/patches/tvheadend42-02_makefile_ffmpeg.patch
Labels: ADDONS, LE 8.2

#2659 documentation: package.mk
  packages/addons/README.md
  packages/packages.mk.addon_template
  packages/packages.mk.template
  packages/readme.md
Labels: BUILDSYSTEM, DOCUMENTATION

#2679 eventlircd: don't grab power buttons
  packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
Labels: CLEANUP, LE 9.0

#2732 scripts/image: fix noobs tarball
  scripts/image
Labels: BUGFIX, BUILDSYSTEM, LE 9.0

#2726 libdrm: change to use meson and update
  packages/graphics/libdrm/package.mk
Labels: LE 9.0, PACKAGE, UPDATE

#2734 openssl: do not include from host
  packages/security/openssl/package.mk
Labels: BUGFIX, LE 9.0
