Repository LibreELEC/LibreELEC.tv, pull requests merged in 2019-02, with the labels that each got.

#3289 linux: add patch to fix Zotac IR remotes
  packages/linux-driver-addons/dvb/depends/media_tree/patches/media_tree-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
  packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
  packages/linux-driver-addons/dvb/depends/media_tree_cc_aml/patches/media_tree_cc_aml-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
  packages/linux/patches/default/linux-902-extend-rc6-toggle-support-for-zotac.patch
  packages/linux/patches/raspberrypi/linux-902-extend-rc6-toggle-support-for-zotac.patch
Labels: BACKPORT DONE, BACKPORT REQD, BUGFIX, KERNEL, LE 9.2

#3283 config/functions: add cross-compile property support
  config/functions
Labels: BACKPORT DONE, BUILDSYSTEM, IMPROVEMENT, LE 9.2

#3282 mesa: update to mesa-18.3.3
  packages/graphics/mesa/package.mk
Labels: LE 9.2, PACKAGE, UPDATE

#3284 libva: update to libva-2.4.0
  packages/debug/libva-utils/package.mk
  packages/multimedia/libva/package.mk
Labels: LE 9.2, PACKAGE, UPDATE

#3287 distro: bump OS_VERSION/ADDON_VERSION to 9.1
  distributions/LibreELEC/version
Labels: BUILDSYSTEM, LE 9.2

#3294 buildsystem: fixes as required
  config/multithread
  packages/addons/addon-depends/ffmpegx-depends/libvpx/package.mk
  packages/addons/addon-depends/network-tools-depends/nmap/package.mk
  packages/addons/service/mpd/package.mk
  packages/addons/service/slice/package.mk
  packages/devel/flex/package.mk
  packages/devel/libtool/package.mk
  packages/linux-firmware/slice-firmware/package.mk
  packages/multimedia/aom/package.mk
  packages/readme.md
  packages/tools/led_tools/package.mk
  packages/tools/slice-addon/package.mk
  scripts/build
  scripts/create_addon
  scripts/create_addon_st
  scripts/image
  scripts/unpack
  tools/dashboard
  tools/pkgcheck
Labels: BUILDSYSTEM, LE 9.2

#3314 emby4: update to 4.0.2.0
  packages/addons/service/emby4/changelog.txt
  packages/addons/service/emby4/package.mk
Labels: ADDONS, LE 9.2, UPDATE

#3308 nano: disable line wrapping
  packages/tools/nano/package.mk
Labels: BACKPORT DONE, BUGFIX, LE 9.2

#3309 nano: disable line wrapping
  packages/tools/nano/package.mk
Labels: BUGFIX, LE 9.0

#3318 buildsystem: add multithreaded ad-hoc package build
  scripts/build_mt
  tools/mtstats.py
Labels: BUILDSYSTEM, IMPROVEMENT, LE 9.2

#3312 buildsystem: fix debug broken by #3171
  config/functions
  config/options
Labels: BUGFIX, BUILDSYSTEM, LE 9.2

#3313 buildsystem: fix debug broken by #3171 [backport]
  config/functions
  config/options
Labels: BUGFIX, BUILDSYSTEM, LE 9.0

#3304 libnfs: update to libnfs-4.0.0
  packages/network/libnfs/package.mk
Labels: LE 9.2, PACKAGE, UPDATE

#3290 openssl: update SSL CA trust store (sync with Kodi PR15441)
  packages/security/openssl/cert/cacert.pem
Labels: LE 9.0, UPDATE

#3285 config/functions: add cross-compile property support [backport]
  config/functions
Labels: BUILDSYSTEM, IMPROVEMENT, LE 9.0

#3293 [le9.0] add patch to fix Zotac IR remotes
  packages/linux-driver-addons/dvb/depends/media_tree/patches/media_tree-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
  packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
  packages/linux-driver-addons/dvb/depends/media_tree_cc_aml/patches/media_tree_cc_aml-03-linux-902-extend-rc6-toggle-support-for-zotac.patch
  packages/linux/patches/default/linux-902-extend-rc6-toggle-support-for-zotac.patch
  packages/linux/patches/raspberrypi/linux-902-extend-rc6-toggle-support-for-zotac.patch
Labels: BUGFIX, KERNEL, LE 9.0

#3300 [le92] kodi: update to 18.1
  packages/mediacenter/kodi/package.mk
Labels: BACKPORT DONE, BACKPORT REQD, LE 9.2, PACKAGE, UPDATE

#3301 [le90] kodi: update to 18.1
  packages/mediacenter/kodi/package.mk
Labels: LE 9.0, PACKAGE, UPDATE

#3319 buildsystem: more fixes as required
  config/functions
  packages/addons/addon-depends/system-tools-depends/encfs/package.mk
Labels: BUILDSYSTEM, LE 9.2

#3321 CrazyCat TBS 5520SE fix
  packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-04-fix-tbs5520se.patch
  packages/linux-driver-addons/dvb/depends/media_tree_cc_aml/patches/media_tree_cc_aml-04-fix-tbs5520se.patch
Labels: BACKPORT DONE, BUGFIX, LE 9.2

#3320 CrazyCat TBS 5520SE fix
  packages/linux-driver-addons/dvb/depends/media_tree_cc/patches/media_tree_cc-04-fix-tbs5520se.patch
  packages/linux-driver-addons/dvb/depends/media_tree_cc_aml/patches/media_tree_cc_aml-04-fix-tbs5520se.patch
Labels: BUGFIX, LE 9.0

#3260 linux (RPi/Generic): update to linux-4.19.21
  packages/graphics/bcm2835-driver/package.mk
  packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
  packages/linux-firmware/kernel-firmware/firmwares/x86_64.dat
  packages/linux-firmware/kernel-firmware/package.mk
  packages/linux-firmware/kernel-firmware/patches/kernel-firmware-01-add-vega20-firmwares.patch
  packages/linux/package.mk
  packages/tools/bcm2835-bootloader/package.mk
  projects/RPi/devices/RPi/linux/linux.arm.conf
  projects/RPi/devices/RPi2/linux/linux.arm.conf
Labels: KERNEL, LE 9.2, PACKAGE, UPDATE, WORK IN PROGRESS

#3296 kodi: cleanup Lircmap.xml patch
  packages/mediacenter/kodi/patches/kodi-995.10-devinputmappings.patch
Labels: BACKPORT DONE, BACKPORT REQD, BUGFIX, CLEANUP, LE 9.2

#3297 [le90] kodi: cleanup Lircmap.xml patch
  packages/mediacenter/kodi/patches/kodi-995.10-devinputmappings.patch
Labels: BUGFIX, CLEANUP, LE 9.0

#3323 linux (RPi/Generic): update to 4.19.23 [backport]
  packages/graphics/bcm2835-driver/package.mk
  packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
  packages/linux-firmware/kernel-firmware/firmwares/x86_64.dat
  packages/linux-firmware/kernel-firmware/package.mk
  packages/linux-firmware/kernel-firmware/patches/kernel-firmware-01-add-vega20-firmwares.patch
  packages/linux/package.mk
  packages/tools/bcm2835-bootloader/package.mk
  projects/RPi/devices/RPi/linux/linux.arm.conf
  projects/RPi/devices/RPi2/linux/linux.arm.conf
Labels: KERNEL, LE 9.0, PACKAGE, UPDATE

#3306 kodi.sh: upgrade crash log information
  packages/mediacenter/kodi/scripts/kodi.sh
Labels: BACKPORT DONE, FEATURE, LE 9.2

#3337 librespot: update to daeeeaa (22-02-2019)
  packages/addons/service/librespot/changelog.txt
  packages/addons/service/librespot/package.mk
Labels: ADDONS, BACKPORT DONE, BUGFIX, LE 9.2, UPDATE

#3339 Backport of #3337
  packages/addons/service/librespot/changelog.txt
  packages/addons/service/librespot/package.mk
Labels: ADDONS, BUGFIX, LE 9.0, UPDATE

#3341 packages: fix dependencies [backport]
  packages/addons/addon-depends/network-tools-depends/nmap/package.mk
  packages/addons/addon-depends/system-tools-depends/encfs/package.mk
  packages/addons/service/mpd/package.mk
  packages/audio/libopenmpt/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.asterwave/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.cpblobs/package.mk
  packages/multimedia/aom/package.mk
Labels: LE 9.0, PACKAGE

#3322 mesa: update to mesa-18.3.4
  packages/graphics/mesa/package.mk
Labels: LE 9.2, PACKAGE, UPDATE

#3307 kodi.sh: upgrade crash log information
  packages/mediacenter/kodi/scripts/kodi.sh
Labels: FEATURE, LE 9.0

#3328 buildsystem: use isolated sysroot for installation
  config/functions
  config/multithread
  packages/addons/addon-depends/libimobiledevice/package.mk
  packages/addons/addon-depends/qtbase/package.mk
  packages/audio/libopenmpt/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.asterwave/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.cpblobs/package.mk
  scripts/build
  scripts/genbuildplan.py
  scripts/image
  scripts/unpack
Labels: BUGFIX, BUILDSYSTEM, LE 9.2, PACKAGE, UPDATE

#3343 rpi-tools: update gpiozero to not require setuptools
  packages/addons/addon-depends/rpi-tools-depends/colorzero/package.mk
  packages/addons/addon-depends/rpi-tools-depends/gpiozero/package.mk
  packages/addons/tools/rpi-tools/changelog.txt
  packages/addons/tools/rpi-tools/package.mk
Labels: ADDONS, BUGFIX, UPDATE

#3344 rpi-tools: update gpiozero to not require setuptools
  packages/addons/addon-depends/rpi-tools-depends/colorzero/package.mk
  packages/addons/addon-depends/rpi-tools-depends/gpiozero/package.mk
  packages/addons/tools/rpi-tools/changelog.txt
  packages/addons/tools/rpi-tools/package.mk
Labels: ADDONS, BUGFIX, UPDATE

#3345 texturecache.py: update to texturecache.py-2.4.9
  packages/tools/texturecache.py/package.mk
Labels: BACKPORT DONE, LE 9.2, PACKAGE, UPDATE

#3346 texturecache.py: update to texturecache.py-2.4.9 [backport]
  packages/tools/texturecache.py/package.mk
Labels: LE 9.0, PACKAGE, UPDATE
