Repository LibreELEC/LibreELEC.tv, pull requests merged in 2020-09, with the labels that each got.

#4544 Allwinner: Add support for R40 SoC
  packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
  packages/linux-firmware/brcmfmac_sdio-firmware/scripts/brcmfmac-firmware-setup
  projects/Allwinner/devices/R40/filesystem/usr/share/alsa/cards/H3_Audio_Codec.conf
  projects/Allwinner/devices/R40/options
  projects/Allwinner/devices/R40/patches/linux/0015-clk-r40-initialize-clocks-earlier.patch
  projects/Allwinner/devices/R40/patches/linux/0016-dts-enable-various-devices.patch
  projects/Allwinner/devices/R40/patches/linux/0017-r40-hdmi-audio-wip.patch
  projects/Allwinner/linux/linux.arm.conf
  projects/Allwinner/patches/linux/0002-backport-from-linux-next.patch
  projects/Allwinner/patches/linux/0006-wip-cec-improvements.patch
  scripts/uboot_helper
Labels: ALLWINNER, HARDWARE, IMPROVEMENT, LE 10.0

#4521 python: update to 3.8.5
  packages/lang/Python3/package.mk
  packages/lang/Python3/patches/Python3-0000-default-is-optimized.patch
  packages/lang/Python3/patches/Python3-0100-buildroot-patches.patch
  packages/lang/Python3/patches/Python3-0201-xcompile.patch
  packages/lang/Python3/patches/Python3-0202-xcompile.patch
  packages/python/system/dbus-python/package.mk
Labels: LE 10.0

#4545 linux: update to 5.8.7
  packages/linux/package.mk
Labels: KERNEL, LE 10.0, UPDATE

#4546 add support for SKY-Q remote
  packages/sysutils/eventlircd/evmap/skyqremote.evmap
  packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
Labels: LE 10.0

#4540 use a systemd generator for selecting the default target
  packages/sysutils/busybox/package.mk
  packages/sysutils/busybox/scripts/init
  packages/sysutils/busybox/scripts/libreelec-target-generator
Labels: BUGFIX, LE 10.0

#4551 connman/wireguard package bumps
  packages/network/connman/package.mk
  packages/network/wireguard-linux-compat/package.mk
  packages/network/wireguard-tools/config/wireguard/wireguard.config.sample
  packages/network/wireguard-tools/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4550 kodi: don't enable webserver by default
  packages/mediacenter/kodi/config/appliance.xml
Labels: BUGFIX, LE 10.0

#4500 arch.aarch64: don't attempt to use the LSE cpu feature
  config/arch.aarch64
Labels: BUGFIX, LE 10.0

#4553 scripts/mkimage: drop chowning image to SUDO_USER
  scripts/mkimage
Labels: BUILDSYSTEM, CLEANUP, LE 10.0

#4370 addons: drop dependency to LE
  config/addon/xbmc.broken.xml
  config/addon/xbmc.python.module.xml
  config/addon/xbmc.python.script.xml
  config/addon/xbmc.service.library.xml
  config/addon/xbmc.service.pluginsource.xml
  config/addon/xbmc.service.xml
  distributions/LibreELEC/version
  packages/addons/script/script.config.vdr/package.mk
  packages/addons/script/script.config.vdr/sources/addon.xml
  packages/addons/service/touchscreen/addon.xml
  packages/addons/service/tvheadend42/addon.xml
  packages/mediacenter/kodi/config/os.libreelec.tv/addon.xml
  packages/mediacenter/kodi/config/os.openelec.tv/addon.xml
  packages/mediacenter/kodi/package.mk
Labels: ADDONS, CLEANUP, LE 10.0, UPDATE

#4555 kodi update to latest
  packages/addons/service/bluetooth-audio/source/default.py
  packages/addons/service/librespot/source/resources/lib/ls_addon.py
  packages/addons/service/slice/source/default.py
  packages/emulation/libretro-mame2003/package.mk
  packages/emulation/libretro-mame2003_plus/package.mk
  packages/emulation/libretro-mgba/package.mk
  packages/mediacenter/kodi-binary-addons/game.libretro.mame2003/package.mk
  packages/mediacenter/kodi-binary-addons/game.libretro.mame2003_plus/package.mk
  packages/mediacenter/kodi-binary-addons/game.libretro.mgba/package.mk
  packages/mediacenter/kodi-binary-addons/game.libretro.sameboy/package.mk
  packages/mediacenter/kodi-binary-addons/game.libretro/package.mk
  packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk
  packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
  packages/mediacenter/kodi-binary-addons/peripheral.xarcade/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.asteroids/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.asterwave/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.greynetic/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.matrixtrails/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.pingpong/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.shadertoy/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.fishbmc/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.goom/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.pictureit/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.spectrum/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.starburst/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.waveform/package.mk
  packages/mediacenter/kodi/package.mk
  packages/mediacenter/kodi/patches/kodi-001-pr18378-support-libplist-2.2.0.patch
  packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch
  packages/mediacenter/kodi/patches/kodi-100.07-disable-minimize.patch
  packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch
  packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
  projects/RPi/devices/RPi4/patches/kodi/0002-popcornmix-VideoPlayer-Add-setting-to-disable-non-hevc-accel.patch
Labels: ADDONS, LE 10.0, UPDATE

#4556 distro: remove espeak
  distributions/LibreELEC/options
  packages/audio/espeak/package.mk
  packages/audio/espeak/patches/espeak-1.47-ftbs-ld-libm.patch
  packages/audio/espeak/patches/espeak-1.47-wav-close.patch
  packages/audio/espeak/patches/espeak-1.48-gcc-6-fix.patch
  packages/mediacenter/kodi/package.mk
  projects/ARM/options
Labels: CLEANUP, LE 10.0

#4559 brcmfmac_sdio-firmware: update to 4b4acd5
  packages/linux-firmware/brcmfmac_sdio-firmware/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4495 mkimage: really enable debug shell for installer
  scripts/mkimage
Labels: BUGFIX, LE 9.2

#4560 [le92] kodi binary addons: update to latest Leia versions
  packages/mediacenter/kodi-binary-addons/pvr.mythtv/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.asteroids/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.asterwave/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.greynetic/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.matrixtrails/package.mk
  packages/mediacenter/kodi-binary-addons/screensaver.pingpong/package.mk
  packages/mediacenter/kodi-binary-addons/vfs.rar/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.fishbmc/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.goom/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.pictureit/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.shadertoy/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.spectrum/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.starburst/package.mk
  packages/mediacenter/kodi-binary-addons/visualization.waveform/package.mk
Labels: ADDONS, LE 9.2, UPDATE

#4552 connman/wireguard package bumps
  packages/network/connman/package.mk
  packages/network/wireguard-linux-compat/package.mk
  packages/network/wireguard-tools/config/wireguard/wireguard.config.sample
  packages/network/wireguard-tools/package.mk
Labels: LE 9.2, PACKAGE, UPDATE

#4564 Allwinner: Add patch to fix eMMC on some Beelink GS1
  projects/Allwinner/devices/H6/patches/linux/19-Beelink-GS1.patch
Labels: IMPROVEMENT, KERNEL, LE 10.0

#4570 libdrm: update to 2.4.102
  packages/graphics/libdrm/package.mk
Labels: LE 10.0, UPDATE
