Repository LibreELEC/LibreELEC.tv, pull requests merged in 2020-10, with the labels that each got.

#4568 add dbussy python package
  packages/mediacenter/LibreELEC-settings/package.mk
  packages/python/system/dbussy/package.mk
Labels: LE 10.0, PACKAGE

#4569 mesa: update to 20.2.0
  packages/graphics/libglvnd/package.mk
  packages/graphics/mesa/package.mk
Labels: LE 10.0, UPDATE

#4567 systemd: update to v246
  packages/sysutils/systemd/package.mk
  packages/sysutils/systemd/patches/systemd-0001-move-etc-systemd-system-to-storage-.config-system.d.patch
  packages/sysutils/systemd/system.d/hwdb.service
Labels: LE 10.0, UPDATE

#4574 kodi update to latest
  packages/mediacenter/kodi-binary-addons/audiodecoder.sacd/package.mk
  packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.vbox/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.vuplus/package.mk
  packages/mediacenter/kodi/package.mk
  packages/mediacenter/kodi/patches/kodi-100.03-disable-online-check.patch
  packages/mediacenter/kodi/patches/kodi-100.09-use-a-wrapper-to-setup-service-addons.patch
  packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
Labels: LE 10.0, UPDATE

#4577 Graphics related package updates
  packages/debug/libva-utils/package.mk
  packages/lang/llvm/package.mk
  packages/multimedia/gmmlib/package.mk
  packages/multimedia/libva/package.mk
  packages/multimedia/libvdpau/package.mk
  packages/multimedia/media-driver/package.mk
  packages/x11/driver/xf86-video-intel/package.mk
Labels: LE 10.0, UPDATE

#4578 linux: add IOMMU support for Generic
  projects/Generic/linux/linux.x86_64.conf
Labels: BUGFIX, KERNEL, LE 10.0

#4586 linux: leave Intel IOMMU default off for Generic
  projects/Generic/linux/linux.x86_64.conf
Labels: IMPROVEMENT, KERNEL, LE 10.0

#4584 LibreELEC-settings: update to db28885
  packages/mediacenter/LibreELEC-settings/package.mk
Labels: LE 10.0, UPDATE

#4587 linux-firmware: pick mrvl/sd8897_uapsta.bin for Generic
  packages/linux-firmware/kernel-firmware/firmwares/x86_64.dat
Labels: FEATURE, HARDWARE, LE 10.0

#4579 [getedid] remove kernel check
  packages/sysutils/busybox/scripts/getedid
Labels: CLEANUP, LE 10.0

#4566 RPi: remove Slice and Slice3 devices
  packages/addons/service/slice/changelog.txt
  packages/addons/service/slice/icon/icon.png
  packages/addons/service/slice/package.mk
  packages/addons/service/slice/source/default.py
  packages/addons/service/slice/source/resources/media/ledpatterns/ffwd.png
  packages/addons/service/slice/source/resources/media/ledpatterns/pause.png
  packages/addons/service/slice/source/resources/media/ledpatterns/play.png
  packages/addons/service/slice/source/resources/media/ledpatterns/quit.png
  packages/addons/service/slice/source/resources/media/ledpatterns/rew.png
  packages/addons/service/slice/source/resources/media/ledpatterns/shutdown.png
  packages/addons/service/slice/source/resources/media/ledpatterns/skipf.png
  packages/addons/service/slice/source/resources/media/ledpatterns/skipr.png
  packages/addons/service/slice/source/resources/media/ledpatterns/sleep.png
  packages/addons/service/slice/source/resources/media/ledpatterns/startup.png
  packages/addons/service/slice/source/resources/media/ledpatterns/stop.png
  packages/addons/service/slice/source/resources/media/ledpatterns/wake.png
  packages/linux-drivers/slice-drivers/package.mk
  packages/linux-firmware/slice-firmware/package.mk
  packages/mediacenter/kodi/package.mk
  packages/tools/bcm2835-bootloader/package.mk
  packages/tools/bcm2835-bootloader/release
  packages/tools/led_tools/package.mk
  projects/RPi/bootloader/update.sh
  projects/RPi/devices/Slice/config/distroconfig.txt
  projects/RPi/devices/Slice/filesystem/usr/config/autostart.sh
  projects/RPi/devices/Slice/filesystem/usr/config/shutdown.sh
  projects/RPi/devices/Slice/filesystem/usr/share/alsa/cards/snd_slice.conf
  projects/RPi/devices/Slice/linux
  projects/RPi/devices/Slice/options
  projects/RPi/devices/Slice/patches/kodi/kodi-004-keyboard.patch
  projects/RPi/devices/Slice/patches/linux/linux-05-cs4265-c.patch
  projects/RPi/devices/Slice/patches/linux/linux-999.99-slice-mmc-aliases.patch
  projects/RPi/devices/Slice3/config/distroconfig.txt
  projects/RPi/devices/Slice3/filesystem/usr/config/autostart.sh
  projects/RPi/devices/Slice3/filesystem/usr/config/shutdown.sh
  projects/RPi/devices/Slice3/filesystem/usr/share/alsa/cards/snd_slice.conf
  projects/RPi/devices/Slice3/linux
  projects/RPi/devices/Slice3/options
  projects/RPi/devices/Slice3/patches/kodi/kodi-004-keyboard.patch
  projects/RPi/devices/Slice3/patches/linux/linux-05-cs4265-c.patch
  projects/RPi/devices/Slice3/patches/linux/linux-999.99-slice-mmc-aliases.patch
  projects/RPi/options
  scripts/image
  scripts/mkimage
Labels: CLEANUP, LE 10.0

#4572 e2fsprogs: update to 1.45.6
  packages/sysutils/e2fsprogs/package.mk
Labels: LE 10.0, UPDATE

#4463 system: accept compressed configuration backups
  packages/mediacenter/LibreELEC-settings/scripts/backup-restore
  packages/sysutils/busybox/scripts/libreelec-target-generator
Labels: IMPROVEMENT, LE 10.0

#4585 Fix kernel 5.8 patch on RTL8192EU and RTL8192DU cleanup
  packages/linux-drivers/RTL8192DU/patches/RTL8192DU-0002-PR61.patch
  packages/linux-drivers/RTL8192DU/patches/RTL8192DU-0003-fix-vfs-read.patch
  packages/linux-drivers/RTL8192DU/patches/RTL8192DU-0004-revert-fix-for-old-kernels.patch
  packages/linux-drivers/RTL8192EU/package.mk
  projects/Amlogic/patches/linux/linux-0001-perf-cs-etm-Move-definition-of-traceid_list-global-v.patch
Labels: HARDWARE, LE 10.0, UPDATE

#4589 add game.libretro.atari800
  packages/emulation/libretro-atari800/package.mk
  packages/mediacenter/kodi-binary-addons/game.libretro.atari800/package.mk
Labels: ADDONS, LE 10.0

#4590 [le92] add game.libretro.atari800
  packages/emulation/libretro-atari800/package.mk
  packages/mediacenter/kodi-binary-addons/game.libretro.atari800/package.mk
Labels: ADDONS, LE 9.2

#4581 [getedid] remove kernel check
  packages/sysutils/busybox/scripts/getedid
Labels: CLEANUP, LE 9.2

#4562 linux (RPi): update to 5.9
  packages/graphics/bcm2835-driver/package.mk
  packages/linux/package.mk
  packages/linux/patches/default/linux-051-ouya_controller_support.patch
  packages/linux/patches/raspberrypi/linux-0001-perf-cs-etm-Move-definition-of-traceid_list-global-v.patch
  packages/linux/patches/raspberrypi/linux-010-hide-4k-modes.patch
  packages/linux/patches/raspberrypi/linux-051-ouya_controller_support.patch
  packages/tools/bcm2835-bootloader/files/3rdparty/bootloader/distroconfig.txt
  packages/tools/bcm2835-bootloader/package.mk
  packages/tools/rpi-eeprom/package.mk
  packages/virtual/network/package.mk
  projects/RPi/devices/RPi/config/distroconfig.txt
  projects/RPi/devices/RPi/linux/linux.arm.conf
  projects/RPi/devices/RPi2/linux/linux.arm.conf
  projects/RPi/devices/RPi4/config/distroconfig.txt
  projects/RPi/devices/RPi4/kodi/appliance.xml
  projects/RPi/devices/RPi4/linux/linux.arm.conf
  projects/RPi/devices/RPi4/patches/kodi/0003-popcornmix-pi4-hack-Try-to-hide-pixel-wrap-issue.patch
Labels: KERNEL, LE 10.0, UPDATE

#4592 wireguard-linux-compat: remove no-longer-needed package
  packages/network/wireguard-linux-compat/modules-load.d/wireguard.conf
  packages/network/wireguard-linux-compat/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4597 connman: minor bump for wireguard ipv6 issue
  packages/network/connman/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4582 systemd: add backport patch to fix device enumeration
  packages/sysutils/systemd/patches/systemd-0100-backport-pr-17267.patch
Labels: BUGFIX, LE 10.0

#4596 u-boot: update to v2020.10
  packages/tools/u-boot/package.mk
  projects/Allwinner/devices/H5/patches/u-boot/0001-OrangePi-PC2-Update-defaults.patch
  projects/Allwinner/devices/H6/patches/u-boot/001-backports.patch
  projects/Amlogic/patches/u-boot/0001-HACK-prevent-stdout-stderr-on-videoconsole.patch
  projects/Amlogic/patches/u-boot/0002-HACK-mmc-meson-gx-limit-to-24MHz.patch
  projects/Amlogic/patches/u-boot/u-boot-0001-FROMGIT-dt-bindings-leds-import-common-led-bindings-.patch
  projects/Amlogic/patches/u-boot/u-boot-0002-FROMGIT-mmc-meson-gx-enable-input-clocks.patch
  projects/Amlogic/patches/u-boot/u-boot-0003-FROMGIT-clk-meson-reset-mmc-clock-on-probe.patch
  projects/Amlogic/patches/u-boot/u-boot-0004-FROMGIT-arm64-dts-meson-sync-dt-and-bindings-from-v5.patch
  projects/Amlogic/patches/u-boot/u-boot-0005-FROMGIT-arm64-dts-meson-import-libretech-pc-from-lin.patch
  projects/Amlogic/patches/u-boot/u-boot-0006-FROMGIT-arm64-dts-meson-add-libretech-pc-support.patch
  projects/Amlogic/patches/u-boot/u-boot-0007-FROMGIT-ARM-dts-add-missing-meson-gxl-s805x-libretec.patch
  projects/Amlogic/patches/u-boot/u-boot-0008-FROMGIT-arm64-dts-meson-gx-add-back-dmc-register-ran.patch
  projects/Amlogic/patches/u-boot/u-boot-0009-FROMGIT-generic-phy-add-generic_phy_get_by_node.patch
  projects/Amlogic/patches/u-boot/u-boot-0010-FROMGIT-phy-meson-gxl-usb-add-set_mode-call-to-force.patch
  projects/Amlogic/patches/u-boot/u-boot-0011-FROMGIT-arm-meson-gx-add-board_usb_init-cleanup-for-.patch
  projects/Amlogic/patches/u-boot/u-boot-0012-FROMGIT-arm-dts-meson-gxl-Add-USB-Gadget-nodes-for-U.patch
  projects/Amlogic/patches/u-boot/u-boot-0013-FROMGIT-configs-libretech-cc-Enable-USB-gadget-with-.patch
  projects/Amlogic/patches/u-boot/u-boot-0014-FROMGIT-configs-libretech-ac-Enable-USB-gadget-with-.patch
  projects/Amlogic/patches/u-boot/u-boot-0015-FROMGIT-configs-khadas-vim2-Enable-USB-gadget-with-M.patch
  projects/Amlogic/patches/u-boot/u-boot-0016-FROMGIT-configs-khadas-vim-Enable-USB-gadget-with-Ma.patch
  projects/Amlogic/patches/u-boot/u-boot-0017-FROMGIT-configs-libretech-s905d-pc-Enable-USB-gadget.patch
  projects/Amlogic/patches/u-boot/u-boot-0018-FROMGIT-configs-libretech-s912-pc-Enable-USB-gadget-.patch
  projects/Amlogic/patches/u-boot/u-boot-0019-FROMGIT-clk-meson-g12a-add-missing-SD_EMMC_A-control.patch
  projects/Amlogic/patches/u-boot/u-boot-0020-FROMGIT-phy-meson-add-GXBB-PHY-driver.patch
  projects/Amlogic/patches/u-boot/u-boot-0021-FROMGIT-arm64-dts-meson-sync-dt-and-bindings-from-v5.patch
  projects/Amlogic/patches/u-boot/u-boot-0022-FROMGIT-arm-dts-meson-gxm-khadas-vim2-u-boot-enable-.patch
  projects/Amlogic/patches/u-boot/u-boot-0023-FROMGIT-configs-khadas-vim2-enable-support-for-SPI-N.patch
  projects/Amlogic/patches/u-boot/u-boot-0024-FROMGIT-arm-dts-meson-khadas-vim3-enable-SPI-NOR-fla.patch
  projects/Amlogic/patches/u-boot/u-boot-0025-FROMGIT-configs-khadas-vim3-enable-support-for-SPI-N.patch
  projects/Amlogic/patches/u-boot/u-boot-0026-FROMGIT-usb-dwc3-meson-g12a-add-power-on-off-of-the-.patch
  projects/Amlogic/patches/u-boot/u-boot-0027-FROMGIT-odroid-c2-enable-USB-host-controller.patch
  projects/Amlogic/patches/u-boot/u-boot-0028-FROMGIT-ARM-dts-Import-Odroid-C4-DT-from-Linux-5.X.patch
  projects/Amlogic/patches/u-boot/u-boot-0029-FROMGIT-boards-amlogic-add-Odroid-C4-support.patch
  projects/Amlogic/patches/u-boot/u-boot-0030-FROMGIT-arm-dts-khadas-vim3-include-meson-g12-common.patch
  projects/Amlogic/patches/u-boot/u-boot-0031-FROMGIT-configs-khadas-vim3-enable-HDMI-output.patch
  projects/Amlogic/patches/u-boot/u-boot-0033-HACK-prevent-stdout-stderr-on-videoconsole.patch
Labels: ALLWINNER, AMLOGIC, LE 10.0, UPDATE

#4600 bcm_sta: fix building on Linux 5.9
  packages/linux-drivers/bcm_sta/patches/bcm_sta-0400-kernel-5.9-fix.patch
Labels: GENERIC, LE 10.0, PATCH

#4594 Generic, Allwinner, Rockchip: Update to Linux 5.9
  packages/linux/package.mk
  packages/x11/driver/xf86-video-nvidia-legacy/patches/xf86-video-nvidia-legacy-0005-fix-5.9.patch
  packages/x11/driver/xf86-video-nvidia/package.mk
  packages/x11/driver/xf86-video-nvidia/udev.d/96-nvidia.rules
  projects/Allwinner/devices/A64/patches/linux/03_pine64_plus_ethernet_fixes.patch
  projects/Allwinner/linux/linux.aarch64.conf
  projects/Allwinner/linux/linux.arm.conf
  projects/Allwinner/patches/linux/0003-hdmi-improvements.patch
  projects/Allwinner/patches/linux/0007-drm-fixes.patch
  projects/Generic/linux/linux.x86_64.conf
  projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf
  projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf
  projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf
  projects/Rockchip/patches/linux/default/linux-0001-rockchip-from-5.10.patch
  projects/Rockchip/patches/linux/default/linux-0001-rockchip-from-5.9.patch
  projects/Rockchip/patches/linux/default/linux-0002-rockchip-from-next.patch
  projects/Rockchip/patches/linux/default/linux-0011-v4l2-from-5.10.patch
  projects/Rockchip/patches/linux/default/linux-0011-v4l2-from-5.9.patch
  projects/Rockchip/patches/linux/default/linux-0021-drm-from-5.10.patch
  projects/Rockchip/patches/linux/default/linux-0021-drm-from-5.9.patch
  projects/Rockchip/patches/linux/default/linux-0022-drm-from-next.patch
Labels: ALLWINNER, IMPROVEMENT, KERNEL, LE 10.0

#4598 Allwinner: H6: u-boot: fix rate DDR3 init issues
  projects/Allwinner/devices/H6/patches/u-boot/008-wip-h6-dram-fix.patch
Labels: ALLWINNER, BUGFIX, LE 10.0, hacktoberfest

#4602 Allwinner: H6: Temporar disable HS-DDR mode for eMMC
  projects/Allwinner/devices/H6/patches/linux/19-Beelink-GS1.patch
  projects/Allwinner/devices/H6/patches/linux/20-mmc-sunxi-fix-unusuable-eMMC-on-some-H6-boards-by-disabling-DDR.patch
Labels: ALLWINNER, BUGFIX, LE 10.0

#4605 systemd: backport cache timestamp fixes from master
  packages/sysutils/systemd/patches/systemd-0101-backport-pr-16648-16885.patch
Labels: BUGFIX, LE 10.0

#4583 linux: Haswell black screen fix for Generic
  projects/Generic/patches/linux/linux-100-temporary_i915_haswell_black_screen_fix.patch
Labels: BUGFIX, LE 10.0

#4595 October package updates
  packages/compress/zstd/package.mk
  packages/databases/sqlite/package.mk
  packages/network/openssh/package.mk
  packages/print/freetype/package.mk
  packages/security/gnutls/package.mk
  packages/security/libgpg-error/package.mk
  packages/security/openssl/package.mk
  packages/sysutils/tz/package.mk
  packages/web/curl/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4601 kodi: move environment variables in systemd unit to environment file
  packages/mediacenter/kodi/config/kodi.conf
  packages/mediacenter/kodi/package.mk
  packages/mediacenter/kodi/system.d/kodi.service
Labels: BUGFIX, CLEANUP, LE 10.0

#4611 README: revise general text and credit OpenBricks/GeeXboX build system in copyright
  README.md
Labels: BUILDSYSTEM, LE 10.0

#4617 kernel-firmware: Update to 20200918
  packages/linux-firmware/kernel-firmware/package.mk
Labels: LE 10.0, UPDATE

#4604 October Package Updates 2: Electric Boogaloo
  packages/addons/tools/network-tools/changelog.txt
  packages/addons/tools/network-tools/package.mk
  packages/devel/libfmt/package.mk
  packages/devel/spdlog/package.mk
  packages/graphics/mesa/package.mk
  packages/network/rsync/package.mk
  packages/network/samba/package.mk
Labels: LE 10.0, UPDATE

#4616 visualisation.spectrum: add missing glm dependency
  packages/mediacenter/kodi-binary-addons/visualization.spectrum/package.mk
Labels: ADDONS, BUILDSYSTEM, LE 9.2

#4614 [le92] rpi-eeprom: update to latest version
  packages/tools/rpi-eeprom/package.mk
Labels: LE 9.2, UPDATE

#4612 update_retroplayer-addons: match lastest tag with kodi branch in name
  tools/mkpkg/update_common_functions
  tools/mkpkg/update_retroplayer-addons
Labels: BUGFIX, LE 10.0

#4606 ffmpeg, Allwinner: Update H264 request API patches
  packages/multimedia/ffmpeg/patches/v4l2-request/ffmpeg-001-v4l2-request.patch
  projects/Allwinner/patches/linux/0001-backport-from-5.10.patch
  projects/Allwinner/patches/linux/0002-backport-from-linux-next.patch
  projects/Allwinner/patches/linux/0005-cedrus-improvements.patch
  tools/ffmpeg/gen-patches.sh
Labels: ALLWINNER, LE 10.0, UPDATE

#4624 [le92] kodi binary addons: update to latest Leia versions
  packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.sledovanitv.cz/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.zattoo/package.mk
Labels: ADDONS, LE 9.2, UPDATE

#4622 [le92] kodi: update to 18.9-Leia
  packages/mediacenter/kodi/package.mk
Labels: LE 9.2, UPDATE

#4557 Don't define -DMINIMAL=ON for tini
  packages/addons/addon-depends/tini/package.mk
Labels: BUGFIX, LE 10.0

#4588 tini: don't define -DMINIMAL=ON
  packages/addons/addon-depends/tini/package.mk
  packages/addons/service/docker/changelog.txt
  packages/addons/service/docker/package.mk
Labels: ADDONS, BUGFIX, LE 9.2

#4549 Fix tvheadend42 query urls
  packages/addons/service/tvheadend42/changelog.txt
  packages/addons/service/tvheadend42/package.mk
  packages/addons/service/tvheadend42/patches/tvheadend42-05-webui-query-url-fix.patch
Labels: ADDONS, BUGFIX, LE 9.2

#4619 Allwinner: Fix ethernet across the boards
  projects/Allwinner/devices/A64/patches/linux/03_pine64_plus_ethernet_fixes.patch
  projects/Allwinner/linux/linux.arm.conf
  projects/Allwinner/patches/linux/0008-ethernet-fixes.patch
Labels: ALLWINNER, BUGFIX, LE 10.0

#4625 Allwinner: Remove support for A20
  projects/Allwinner/devices/A20/filesystem/usr/share/alsa/cards/sun4i-hdmi.conf
  projects/Allwinner/devices/A20/options
  projects/Allwinner/devices/A20/patches/linux/0001-disp-fix.patch
  projects/Allwinner/devices/A20/patches/linux/0002-Add-support-for-sun4i-HDMI-audio.patch
  projects/Allwinner/linux/linux.arm.conf
  scripts/uboot_helper
Labels: ALLWINNER, HARDWARE, LE 10.0

#4618 RTL8812AU: Change source code to aircrack-ng
  packages/linux-drivers/RTL8812AU/package.mk
Labels: LE 10.0, UPDATE

#4623 RTL8188EU: Update to c928027
  packages/linux-drivers/RTL8188EU/package.mk
  packages/linux-drivers/RTL8188EU/patches/fix-build-with-5.8.patch
Labels: LE 10.0, UPDATE

#4626 bump kernel-firmware and drop qca-firmware
  packages/linux-firmware/kernel-firmware/package.mk
  packages/linux-firmware/qca-firmware/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4629 kmscube: bump to HEAD and revise package
  packages/graphics/kmscube/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4631 Allwinner: H6: Fix OrangePi 3 ethernet
  projects/Allwinner/devices/H6/patches/linux/07-opi3.patch
  projects/Allwinner/patches/linux/0109-drm-shme-helpers-Fix-dma_buf_mmap-forwarding-bug.patch
Labels: ALLWINNER, BUGFIX, LE 10.0

#4573 Docker: Update default.py to fix Python BPO - syntax warning for "is" with a literal
  packages/addons/service/docker/changelog.txt
  packages/addons/service/docker/package.mk
  packages/addons/service/docker/source/default.py
Labels: ADDONS, BUGFIX, LE 10.0
