Repository LibreELEC/LibreELEC.tv, pull requests merged in 2020-12, with the labels that each got.

#4701 Allwinner: H3 and H6 HW deinterlacing support
  projects/Allwinner/linux/linux.aarch64.conf
  projects/Allwinner/patches/ffmpeg/0001-WIP-deint-filter.patch
  projects/Allwinner/patches/ffmpeg/0002-libavfilter-v4l2deinterlace-dequeue-both-destination.patch
  projects/Allwinner/patches/kodi/0001-WIP-DVDVideoCodecDRMPRIME-add-support-for-filters.patch
  projects/Allwinner/patches/kodi/0002-WIP-DRMPRIME-deinterlace-filter.patch
  projects/Allwinner/patches/linux/x0001-wip-H6-deinterlace.patch
  projects/Allwinner/patches/linux/x0002-arm64-dts-h6-deinterlace.patch
Labels: ALLWINNER, IMPROVEMENT, LE 10.0

#4680 Allwinner: H2-plus: fix bluetooth audio stutter
  projects/Allwinner/devices/H2-plus/patches/linux/01-increase-bt-speed.patch
Labels: BUGFIX, LE 10.0

#4662 busybox: rework device-tree helper scripts
  packages/sysutils/busybox/package.mk
  packages/sysutils/busybox/scripts/dtfile
  packages/sysutils/busybox/scripts/dthelper
  packages/sysutils/busybox/scripts/dtname
  packages/sysutils/busybox/scripts/dtsoc
Labels: IMPROVEMENT, LE 10.0, PACKAGE

#4705 settings: bump to include stats flag change
  packages/mediacenter/LibreELEC-settings/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4707 Intel graphics updates - xf86 and gpu tools
  packages/debug/xorg-intel-gpu-tools/package.mk
  packages/x11/driver/xf86-video-intel/package.mk
Labels: LE 10.0, UPDATE

#4706 ninja: update to v1.10.2
  packages/python/devel/ninja/package.mk
Labels: LE 10.0, UPDATE

#4708 xorg-server: update to 1.20.10
  packages/x11/xserver/xorg-server/package.mk
Labels: LE 10.0, UPDATE

#4709 libX11: update to 1.6.12
  packages/x11/lib/libX11/package.mk
Labels: LE 10.0, UPDATE

#4714 openssl: update cacert.pem
  packages/security/openssl/cert/cacert.pem
Labels: IMPROVEMENT, LE 10.0, PACKAGE

#4716 cmake: fix site and download URL
  packages/devel/cmake/package.mk
Labels: BUGFIX, LE 10.0

#4682 Fix firmwares loading for iMX6
  packages/linux/package.mk
  projects/NXP/devices/iMX6/firmwares/brcmfmac_sdio-firmware.dat
  projects/NXP/devices/iMX6/linux/linux.arm.conf
  projects/NXP/devices/iMX6/patches/linux/linux-001-imx6qdl-wandboard-revc1-dtsi-bluetooth.patch
  projects/NXP/devices/iMX6/patches/linux/linux-011-imx6qdl-sr-som-brcm-dtsi-bluetooth.patch
  projects/NXP/options
Labels: BUGFIX, LE 10.0

#4729 bcm2835-bootloader: config.txt cosmetics
  packages/tools/bcm2835-bootloader/files/config.txt
Labels: DOCUMENTATION, LE 10.0

#4731 busybox: add fsl to dthelper compatibles
  packages/sysutils/busybox/scripts/dthelper
Labels: IMPROVEMENT, LE 10.0, PACKAGE

#4730 media-driver: update to 20.4.3
  packages/multimedia/gmmlib/package.mk
  packages/multimedia/libva/package.mk
  packages/multimedia/media-driver/package.mk
Labels: LE 10.0, UPDATE

#4720 samba: update to current stable 4.13.2
  packages/network/samba/package.mk
  packages/network/samba/patches/samba-950-no-man.patch
  packages/network/samba/patches/samba-951-no-man-4.13.patch
Labels: LE 10.0, UPDATE

#4711 Ensure that the OSMC remote keymap works when using an international keyboard layout
  packages/sysutils/eventlircd/evmap/osmc_rf.evmap
  packages/sysutils/eventlircd/evmap/osmc_rf2.evmap
  packages/sysutils/eventlircd/udev.d/98-eventlircd.rules
  packages/sysutils/systemd/config/hwdb.d/99-osmcrf.hwdb
Labels: CLEANUP, FEATURE, LE 10.0

#4721 util-linux: update to 2.36.1
  packages/sysutils/util-linux/package.mk
Labels: LE 10.0, UPDATE

#4733 LibreELEC-settings: update to 2a08f09 (first working dbussy implemen…
  packages/mediacenter/LibreELEC-settings/package.mk
Labels: BUGFIX, FEATURE, LE 10.0, UPDATE

#4710 gtk3: update to 3.24.23
  packages/addons/addon-depends/chrome-depends/gtk3/package.mk
  packages/addons/addon-depends/chrome-depends/gtk3/patches/gtk3-subdirs.patch
Labels: ADDONS, LE 10.0, UPDATE

#4704 chrome: update to 87 and using fixed versions / minor downloader fixes
  packages/addons/browser/chrome/changelog.txt
  packages/addons/browser/chrome/package.mk
  packages/addons/browser/chrome/source/bin/chrome-downloader
Labels: ADDONS, LE 9.2, UPDATE

#4702 chrome: update to 87 and using fixed versions
  packages/addons/browser/chrome/changelog.txt
  packages/addons/browser/chrome/package.mk
  packages/addons/browser/chrome/source/bin/chrome-downloader
Labels: ADDONS, BACKPORT DONE, LE 10.0, UPDATE

#4712 docker: update to 19.03.14 // including supporting packages
  packages/addons/addon-depends/containerd/package.mk
  packages/addons/addon-depends/go/package.mk
  packages/addons/addon-depends/libnetwork/package.mk
  packages/addons/addon-depends/runc/package.mk
  packages/addons/addon-depends/runc/patches/runc-001-reenable-systemd-on-static-build.patch
  packages/addons/service/docker/changelog.txt
  packages/addons/service/docker/package.mk
Labels: ADDONS, LE 10.0, UPDATE

#4726 Fix Rock Pi 4 nightly builds
  projects/Rockchip/devices/RK3399/README.md
  scripts/uboot_helper
Labels: BUGFIX, LE 10.0, ROCKCHIP

#4739 openssh: ensure tmpfiles.d completes before sshd starts
  packages/network/openssh/system.d/sshd.service
Labels: BUGFIX, LE 10.0, PACKAGE

#4713 mesa: bump to 20.3.0 and change source url
  packages/graphics/mesa/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4734 openssl: update to 1.1.1i
  packages/security/openssl/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4735 openvpn: update to 2.4.10
  packages/network/openvpn/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4740 Update database packages
  packages/addons/service/mariadb/changelog.txt
  packages/addons/service/mariadb/package.mk
  packages/addons/service/mariadb/patches/mariadb-0001-disable-plugin-auth-pam.patch
  packages/databases/mariadb-connector-c/package.mk
  packages/databases/sqlite/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4736 dav1d: updated to 0.8.0
  packages/multimedia/dav1d/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4748 brcmfmac_sdio-firmware-rpi: update to c13705a
  packages/linux-firmware/brcmfmac_sdio-firmware-rpi/package.mk
Labels: LE 10.0, UPDATE

#4749 LibreELEC-settings: update to 4294fe8
  packages/mediacenter/LibreELEC-settings/package.mk
Labels: LE 10.0, UPDATE

#4763 samba: update to 4.13.3
  packages/network/samba/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4745 Compress packages updated
  packages/compress/libarchive/package.mk
  packages/compress/lz4/package.mk
  packages/compress/xz/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4743 Wayland packages updates
  packages/wayland/libinput/package.mk
  packages/wayland/libxkbcommon/package.mk
  packages/wayland/mtdev/package.mk
  packages/wayland/wayland-protocols/package.mk
  packages/wayland/wayland/package.mk
  packages/wayland/waylandpp/package.mk
  packages/wayland/weston/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4744 debug tools - package updates
  packages/debug/gdb/package.mk
  packages/debug/libva-utils/package.mk
  packages/debug/memtester/package.mk
  packages/debug/memtester/patches/memtester-002-fix_GCC10_FTBFS.patch
  packages/debug/valgrind/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4747 python devel - packages updated
  packages/python/devel/Mako/package.mk
  packages/python/devel/distutilscross/package.mk
  packages/python/devel/meson/package.mk
  packages/python/devel/setuptools/package.mk
  packages/python/devel/waf/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4750 Pillow: updated to 8.0.1 and fixed PKG_SITE
  packages/python/graphics/Pillow/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4751 simplejson: update to 3.17.2
  packages/python/system/simplejson/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4757 connman: bump to 40947be3
  packages/network/connman/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4766 glib: update to 2.67.1
  packages/devel/glib/package.mk
Labels: LE 10.0, TOOLCHAIN, UPDATE

#4691 Update RTL wifi drivers to 5.10
  packages/linux-drivers/RTL8192CU/package.mk
  packages/linux-drivers/RTL8192DU/package.mk
  packages/linux-drivers/RTL8192EU/package.mk
  packages/linux-drivers/RTL8812AU/patches/RTL8812AU-0001-fix_kernel_5_10.patch
Labels: BUGFIX, LE 10.0

#4758 Updates to compile with Linux 5.10
  packages/linux-drivers/bcm_sta/patches/bcm_sta-0500-kernel-5.10-fix.patch
  packages/x11/driver/xf86-video-nvidia-legacy/patches/xf86-video-nvidia-legacy-0006-fix-5.10.patch
  packages/x11/driver/xf86-video-nvidia/package.mk
  packages/x11/driver/xf86-video-nvidia/udev.d/96-nvidia.rules
Labels: LE 10.0, PACKAGE, UPDATE

#4759 Allwinner: Update to Linux 5.10
  packages/linux/package.mk
  projects/Allwinner/linux/linux.aarch64.conf
  projects/Allwinner/linux/linux.arm.conf
  projects/Allwinner/patches/linux/0001-backport-from-5.10.patch
  projects/Allwinner/patches/linux/0001-backport-from-5.11.patch
  projects/Allwinner/patches/linux/0005-cedrus-improvements.patch
  projects/Allwinner/patches/linux/0006-wip-cec-improvements.patch
  projects/Allwinner/patches/linux/0007-drm-fixes.patch
Labels: ALLWINNER, KERNEL, LE 10.0, UPDATE

#4760 Generic: update config to Linux 5.10
  projects/Generic/linux/linux.x86_64.conf
Labels: GENERIC, KERNEL, LE 10.0, UPDATE

#4651 linux (RPi): update to 5.10
  packages/graphics/bcm2835-driver/package.mk
  packages/linux/package.mk
  packages/linux/patches/raspberrypi/linux-010-hide-4k-modes.patch
  packages/tools/bcm2835-bootloader/package.mk
  packages/tools/rpi-eeprom/package.mk
  projects/RPi/devices/RPi/linux/linux.arm.conf
  projects/RPi/devices/RPi2/linux/linux.arm.conf
  projects/RPi/devices/RPi4/linux/linux.arm.conf
Labels: KERNEL, LE 10.0, UPDATE

#4675 busybox: rework device-tree helper scripts
  packages/sysutils/busybox/package.mk
  packages/sysutils/busybox/scripts/dtfile
  packages/sysutils/busybox/scripts/dthelper
  packages/sysutils/busybox/scripts/dtname
Labels: IMPROVEMENT, LE 9.2, PACKAGE

#4774 ffmpeg: update rpi patch
  packages/multimedia/ffmpeg/package.mk
  packages/multimedia/ffmpeg/patches/rpi/ffmpeg-001-rpi.patch
  projects/RPi/devices/RPi4/patches/kodi/0002-popcornmix-VideoPlayer-Add-setting-to-disable-non-hevc-accel.patch
  tools/ffmpeg/gen-patches.sh
Labels: BUGFIX, IMPROVEMENT, LE 10.0

#4777 dbus: update to 1.13.18
  packages/sysutils/dbus/package.mk
Labels: LE 10.0, UPDATE

#4782 Allwinner: R40: Enable deinterlace driver
  projects/Allwinner/devices/R40/patches/linux/0018-r40-enable-deinterlace.patch
Labels: ALLWINNER, IMPROVEMENT, KERNEL, LE 10.0

#4783 systemd: fix kernel-overlays.service ordering
  packages/sysutils/systemd/system.d/modprobe@.service.d/dependencies.conf
Labels: BUGFIX, LE 10.0

#4784 Allwinner: Fix and improvement
  projects/Allwinner/devices/H5/patches/linux/18-enable-deinterlace.patch
  projects/Allwinner/patches/linux/0002-media-cedrus-Fix-H264-decoding.patch
Labels: ALLWINNER, BUGFIX, IMPROVEMENT, LE 10.0

#4786 mesa: bump to 20.3.1 for radeonsi fix
  packages/graphics/mesa/package.mk
Labels: BUGFIX, GENERIC, LE 10.0, PACKAGE, UPDATE

#4794 crazycat: update PKG_SITE
  packages/linux-driver-addons/dvb/crazycat/package.mk
Labels: CLEANUP, LE 10.0

#4795 libxkbcommon: fix missing dependency libxml2
  packages/wayland/libxkbcommon/package.mk
Labels: BUGFIX, LE 10.0

#4799 System Tools: add st terminal emulator on Generic (rev 116)
  packages/addons/addon-depends/system-tools-depends/mc/package.mk
  packages/addons/addon-depends/system-tools-depends/st/package.mk
  packages/addons/addon-depends/system-tools-depends/st/patches/st-001-le_fixes.patch
  packages/addons/addon-depends/system-tools-depends/st/patches/st-002-scrollback-20200419-72e3f6c.patch
  packages/addons/addon-depends/system-tools-depends/unrar/package.mk
  packages/addons/addon-depends/system-tools-depends/ytop/package.mk
  packages/addons/tools/system-tools/changelog.txt
  packages/addons/tools/system-tools/package.mk
  packages/addons/tools/system-tools/source/default.py
  packages/devel/ncurses/package.mk
  packages/sysutils/busybox/profile.d/98-busybox.conf
Labels: ADDONS, IMPROVEMENT, LE 10.0, UPDATE

#4770 December package updates
  packages/compress/zstd/package.mk
  packages/sysutils/tz/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4803 cleanup urls and versions
  packages/addons/addon-depends/enet/package.mk
  packages/addons/addon-depends/game-tools/ecm-tools/package.mk
  packages/addons/addon-depends/libdvbcsa/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/tstools/package.mk
  packages/addons/addon-depends/rpi_ws281x/package.mk
  packages/addons/addon-depends/snapcast-depends/asio/package.mk
  packages/addons/addon-depends/system-tools-depends/dstat/package.mk
  packages/addons/addon-depends/system-tools-depends/hddtemp/package.mk
  packages/addons/addon-depends/system-tools-depends/lshw/package.mk
  packages/compress/zip/package.mk
  packages/databases/sqlite/package.mk
  packages/devel/crossguid/package.mk
  packages/devel/libcec/package.mk
  packages/emulation/cyclone68000/package.mk
  packages/emulation/libretro-vram-test/package.mk
  packages/graphics/libprojectM/package.mk
  packages/linux-firmware/misc-firmware/package.mk
  packages/linux-firmware/rtl8723bs_bt/package.mk
  packages/mediacenter/kodi-binary-addons/game.libretro.vram-test/package.mk
  packages/multimedia/libdvdnav/package.mk
  packages/multimedia/libdvdread/package.mk
  packages/multimedia/rtmpdump/package.mk
  packages/network/libdnet/package.mk
  packages/network/wireguard-tools/package.mk
  packages/sysutils/eventlircd/package.mk
  packages/sysutils/irqbalanced/package.mk
  packages/sysutils/irqbalanced/system.d/irqbalance.service
  packages/sysutils/open-iscsi/package.mk
  packages/sysutils/open-vm-tools/package.mk
  packages/textproc/tinyxml/package.mk
  packages/tools/atf/package.mk
  packages/tools/mkbootimg/package.mk
Labels: CLEANUP, LE 10.0

#4804 tinyxml: revert url change
  packages/textproc/tinyxml/package.mk
Labels: BUGFIX, LE 10.0, MERGE ¯\_(ツ)_/¯ 💥

#4781 Update misc-firmware
  packages/linux-firmware/misc-firmware/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4776 libX11: update to 1.7.0
  packages/x11/lib/libX11/package.mk
Labels: LE 10.0, UPDATE

#4812 Drop vsxu and dependancy glfw
  packages/graphics/glfw/package.mk
  packages/graphics/vsxu/package.mk
  packages/graphics/vsxu/patches/vsxu-01-fix-order.patch
  packages/graphics/vsxu/patches/vsxu-02-fix-glfw.patch
  packages/graphics/vsxu/patches/vsxu-03-fix-exr.patch
  packages/graphics/vsxu/patches/vsxu-04-fix-freetype.patch
Labels: CLEANUP, LE 10.0

#4772 libgcrypt: updated to 1.8.7
  packages/security/libgcrypt/package.mk
Labels: LE 10.0, UPDATE

#4746 web package updates
  packages/web/curl/package.mk
  packages/web/nghttp2/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#4762 Allwinner: add support for crust SCP firmware
  packages/lang/gcc-or1k-linux/package.mk
  packages/linux/package.mk
  packages/tools/atf/package.mk
  packages/tools/crust/package.mk
  packages/tools/u-boot/package.mk
  projects/Allwinner/bootloader/firmware
  projects/Allwinner/patches/linux/crust/0001-i2c-mv64xxx-Add-runtime-PM-support.patch
  projects/Allwinner/patches/linux/crust/0002-clk-Implement-protected-clocks-for-all-OF-clock-prov.patch
  projects/Allwinner/patches/linux/crust/0003-Revert-clk-qcom-Support-protected-clocks-property.patch
  projects/Allwinner/patches/linux/crust/0005-DO-NOT-MERGE-ARM-dts-sunxi-h3-h5-Protect-SCP-clocks.patch
  projects/Allwinner/patches/linux/crust/0006-DO-NOT-MERGE-arm64-dts-allwinner-a64-Protect-SCP-clo.patch
  projects/Allwinner/patches/linux/crust/0007-DO-NOT-MERGE-arm64-dts-allwinner-h6-Protect-SCP-cloc.patch
  projects/Allwinner/patches/linux/crust/0008-bus-sunxi-rsb-Always-check-register-address-validity.patch
  projects/Allwinner/patches/linux/crust/0009-bus-sunxi-rsb-Use-devm_platform_ioremap_resource.patch
  projects/Allwinner/patches/linux/crust/0010-bus-sunxi-rsb-Precompute-read-write-commands-and-mas.patch
  projects/Allwinner/patches/linux/crust/0011-bus-sunxi-rsb-Move-OF-match-table.patch
  projects/Allwinner/patches/linux/crust/0012-bus-sunxi-rsb-Split-out-controller-init-exit-functio.patch
  projects/Allwinner/patches/linux/crust/0013-bus-sunxi-rsb-Implement-global-suspend-resume-callba.patch
  projects/Allwinner/patches/linux/crust/0014-bus-sunxi-rsb-Implement-runtime-power-management.patch
  projects/Allwinner/patches/linux/crust/0015-bus-sunxi-rsb-Make-interrupt-handling-more-robust.patch
  projects/Allwinner/patches/linux/crust/0016-irqchip-sun6i-r-Use-a-stacked-irqchip-driver.patch
  projects/Allwinner/patches/linux/crust/0017-irqchip-sun6i-r-Add-wakeup-support.patch
  projects/Allwinner/patches/linux/crust/0018-dt-bindings-irq-Add-a-compatible-for-the-H3-R_INTC.patch
  projects/Allwinner/patches/linux/crust/0019-ARM-dts-sunxi-h3-h5-Add-r_intc-node.patch
  projects/Allwinner/patches/linux/crust/0020-ARM-dts-sunxi-h3-h5-Move-wakeup-capable-IRQs-to-r_in.patch
  projects/Allwinner/patches/linux/crust/0022-arm64-dts-allwinner-a64-Move-wakeup-capable-IRQs-to-.patch
  projects/Allwinner/patches/linux/crust/0023-arm64-dts-allwinner-h6-Fix-indentation-of-IR-node.patch
  projects/Allwinner/patches/linux/crust/0024-arm64-dts-allwinner-h6-Move-wakeup-capable-IRQs-to-r.patch
  projects/Allwinner/patches/linux/crust/0025-rtc-sun6i-Use-wake-IRQ-instead-of-device-PM-ops.patch
  projects/Allwinner/patches/linux/crust/0026-dt-bindings-sram-Add-ARM-SCP-SRAM-compatible.patch
  projects/Allwinner/patches/linux/crust/0027-firmware-arm_scpi-Support-unidirectional-mailbox-cha.patch
  projects/Allwinner/patches/linux/crust/0029-ARM-dts-sunxi-h3-h5-Add-SCPI-protocol.patch
  projects/Allwinner/patches/linux/crust/0030-arm64-dts-allwinner-a64-Add-SCPI-protocol.patch
  projects/Allwinner/patches/linux/crust/0031-arm64-dts-allwinner-h6-Add-SCPI-protocol.patch
  scripts/uboot_helper
Labels: ALLWINNER, IMPROVEMENT, LE 10.0

#4789 kernel-firmware: bump to 20201218
  packages/linux-firmware/kernel-firmware/package.mk
Labels: LE 10.0, UPDATE

#4801 Package updates devel,nano,textproc,libexif
  packages/addons/addon-depends/libexif/package.mk
  packages/devel/bison/package.mk
  packages/devel/flex/package.mk
  packages/devel/flex/patches/c5a26b17a2b091c560f6c4e6703e55f496bf74fa.patch
  packages/devel/flex/patches/flex-001-plex.malloc.patch
  packages/devel/libcap/package.mk
  packages/devel/popt/package.mk
  packages/devel/spdlog/package.mk
  packages/textproc/expat/package.mk
  packages/tools/nano/package.mk
Labels: LE 10.0, UPDATE

#4790 python3: update to 3.8.7
  packages/lang/Python3/package.mk
Labels: LE 10.0, UPDATE

#4796 Update packages/x11 to latest
  packages/x11/app/xkbcomp/package.mk
  packages/x11/driver/xf86-input-libinput/package.mk
  packages/x11/driver/xf86-video-intel/package.mk
  packages/x11/lib/pixman/package.mk
  packages/x11/other/fluxbox/package.mk
Labels: LE 10.0, UPDATE

#4814 Fix package.mk files. Tabs to Spaces
  packages/sysutils/v4l-utils/package.mk
  packages/tools/rpi-eeprom/package.mk
Labels: CLEANUP, LE 10.0

#4695 pulseaudio: update to 14.0
  packages/audio/pulseaudio/package.mk
  packages/audio/pulseaudio/patches/pulseaudio-100.02-check_uid.patch
Labels: LE 10.0, UPDATE

#4817 ncurses: include dumb terminfo again
  packages/devel/ncurses/package.mk
Labels: BUGFIX, LE 10.0

#4768 LibreELEC-settings: set add-on version
  packages/mediacenter/LibreELEC-settings/package.mk
Labels: IMPROVEMENT, LE 10.0, PACKAGE

#4816 linux: Update to 5.10.4
  packages/linux/package.mk
  projects/Allwinner/patches/linux/0009-ir-improvements.patch
Labels: KERNEL, LE 10.0, UPDATE

#4785 update packages/graphics
  packages/graphics/glmark2/package.mk
  packages/graphics/lcms2/package.mk
  packages/graphics/libde265/package.mk
  packages/graphics/libdrm/package.mk
  packages/graphics/libepoxy/package.mk
  packages/graphics/libheif/package.mk
  packages/graphics/libjpeg-turbo/package.mk
  packages/graphics/libprojectM/package.mk
  packages/graphics/libraw/package.mk
  packages/graphics/tiff/package.mk
Labels: LE 10.0, UPDATE

#4820 packages: update readme.md to current version of python
  packages/readme.md
Labels: DOCUMENTATION, LE 10.0

#4791 avahi: update to 0.8 and dependencies
  packages/devel/gettext/package.mk
  packages/network/avahi/package.mk
  packages/network/avahi/patches/avahi-0001_fix-autoconf.patch
  packages/network/libevent/package.mk
Labels: LE 10.0, UPDATE
