Repository LibreELEC/LibreELEC.tv, pull requests merged in 2021-05, with the labels that each got.

#5348 linux (RPi): update to 5.10.33
  packages/graphics/bcm2835-driver/package.mk
  packages/linux/package.mk
  packages/tools/bcm2835-bootloader/package.mk
  packages/tools/rpi-eeprom/package.mk
  projects/RPi/devices/RPi/linux/linux.arm.conf
  projects/RPi/devices/RPi2/linux/linux.arm.conf
  projects/RPi/devices/RPi4/linux/linux.arm.conf
Labels: KERNEL, LE 10.0, UPDATE

#5346 netbase: update to 6.3
  packages/network/netbase/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#5359 kodi-binary-addons: update to latest versions
  packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
Labels: ADDONS, LE 10.0, PACKAGE, UPDATE

#5360 kodi: update to v19.1
  packages/mediacenter/kodi/package.mk
  packages/mediacenter/kodi/patches/kodi-995.20-gbm-default-to-original-crtc-mode.patch
  packages/mediacenter/kodi/patches/kodi-995.30-CDVDVideoCodecDRMPRIME-skip-frames-when-requested.patch
Labels: LE 10.0, PACKAGE, UPDATE

#5343 samba: update to 4.13.8
  packages/network/samba/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#5334 [Allwinner,Generic,Rockchip] linux: Update to 5.10.35
  packages/linux/package.mk
  projects/Allwinner/linux/linux.aarch64.conf
  projects/Allwinner/patches/linux/0056-arm64-dts-allwinner-h6-beelink-gs1-Remove-ext.-32-kH.patch
  projects/Allwinner/patches/linux/0061-arm64-dts-allwinner-Fix-SD-card-CD-GPIO-for-SOPine-s.patch
  projects/Allwinner/patches/linux/0062-arm64-dts-allwinner-Revert-SD-card-CD-GPIO-for-Pine64-LTS.patch
  projects/Amlogic/linux/linux.aarch64.conf
  projects/NXP/devices/iMX8/linux/linux.aarch64.conf
  projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf
  projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf
Labels: KERNEL, LE 10.0, UPDATE

#5362 LibreELEC-settings: update to 3c824b3
  packages/mediacenter/LibreELEC-settings/package.mk
Labels: LE 10.0, UPDATE

#5345 u-boot: rockchip: fix build with GCC 10
  packages/tools/u-boot/patches/rockchip/u-boot-0017-scripts-dtc-Remove-redundant-YYLOC-global-declaratio.patch
Labels: BUGFIX, LE 10.0

#5365 Rockchip update / fixes
  projects/Rockchip/bootloader/install
  projects/Rockchip/devices/RK3288/linux/default/linux.arm.conf
  projects/Rockchip/devices/RK3328/linux/default/linux.aarch64.conf
  projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf
  projects/Rockchip/devices/RK3399/options
  projects/Rockchip/patches/linux/default/linux-0001-rockchip-from-5.11.patch
  projects/Rockchip/patches/linux/default/linux-0002-rockchip-from-5.12.patch
  projects/Rockchip/patches/linux/default/linux-0003-rockchip-from-list.patch
  projects/Rockchip/patches/linux/default/linux-0010-v4l2-from-list.patch
  projects/Rockchip/patches/linux/default/linux-0020-drm-from-5.11.patch
  projects/Rockchip/patches/linux/default/linux-0021-drm-from-list.patch
  projects/Rockchip/patches/linux/default/linux-1001-drm-rockchip.patch
  projects/Rockchip/patches/linux/default/linux-1002-v4l2-rockchip.patch
  projects/Rockchip/patches/linux/default/linux-1003-for-libreelec.patch
  projects/Rockchip/patches/linux/default/linux-2000-v4l-wip-rkvdec-vp9.patch
  projects/Rockchip/patches/linux/default/linux-2001-v4l-wip-rkvdec-hevc.patch
  projects/Rockchip/patches/linux/default/linux-2002-v4l-wip-iep-driver.patch
Labels: BUGFIX, IMPROVEMENT, LE 10.0, ROCKCHIP

#5367 linux (RPi): revert to 5.10.27-7fb9d00
  packages/graphics/bcm2835-driver/package.mk
  packages/linux/package.mk
  packages/tools/bcm2835-bootloader/package.mk
Labels: BUGFIX, KERNEL, LE 10.0

#5363 kodi-binary-addons: update to latest versions
  packages/mediacenter/kodi-binary-addons/inputstream.ffmpegdirect/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.nextpvr/package.mk
Labels: ADDONS, LE 10.0, PACKAGE, UPDATE

#5370 RK fixes
  projects/Rockchip/devices/RK3399/linux/default/linux.aarch64.conf
  projects/Rockchip/patches/linux/default/linux-1001-drm-rockchip.patch
Labels: BUGFIX, LE 10.0, ROCKCHIP

#5374 LibreELEC-settings: update to a702c4d
  packages/mediacenter/LibreELEC-settings/package.mk
Labels: LE 10.0, UPDATE

#5375 kodi-binary-addons: update to latest versions
  packages/mediacenter/kodi-binary-addons/pvr.iptvsimple/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.waipu/package.mk
Labels: ADDONS, LE 10.0, PACKAGE, UPDATE

#5381 kodi-binary-addons: update to latest versions
  packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
  packages/mediacenter/kodi-binary-addons/peripheral.joystick/package.mk
  packages/mediacenter/kodi-binary-addons/pvr.mediaportal.tvserver/package.mk
Labels: ADDONS, LE 10.0, UPDATE

#5384 LibreELEC-settings: update to bfec474
  packages/mediacenter/LibreELEC-settings/package.mk
Labels: LE 10.0, UPDATE

#5385 kodi: update to 2d78f9d
  packages/mediacenter/kodi/package.mk
  packages/mediacenter/kodi/patches/kodi-100.07-disable-minimize.patch
  packages/mediacenter/kodi/patches/kodi-100.10-handle-SIGTERM.patch
Labels: LE 10.0, UPDATE

#5376 [ARM] Add suport for libwidevine.so >= 4.10.2252.0
  config/options
  packages/devel/glibc/patches/arm/glibc-add-support-for-SHT_RELR-sections.patch
  packages/devel/gperftools/package.mk
  packages/virtual/libc/package.mk
Labels: ADDONS, BACKPORT DONE, LE 10.0

#5377 [ARM][9.2] Add suport for libwidevine.so >= 4.10.2252.0
  packages/devel/glibc/patches/arm/glibc-add-support-for-SHT_RELR-sections.patch
  packages/devel/gperftools/package.mk
  packages/virtual/libc/package.mk
Labels: ADDONS, LE 9.2

#5390 kodi-binary-addons: update to latest versions
  packages/mediacenter/kodi-binary-addons/inputstream.adaptive/package.mk
Labels: ADDONS, LE 10.0, PACKAGE, UPDATE

#5391 gperftools: fix for release files
  packages/devel/gperftools/package.mk
Labels: BUGFIX, LE 10.0, MERGE ¯\_(ツ)_/¯ 💥

#5392 gperftools: fix for release files
  packages/devel/gperftools/package.mk
Labels: BUGFIX, LE 9.2

#5394 network-tools: update addon to 109
  packages/addons/addon-depends/network-tools-depends/irssi/package.mk
  packages/addons/addon-depends/network-tools-depends/irssi/patches/001-irssi-1.2.2-glib-2-63.patch
  packages/addons/addon-depends/network-tools-depends/lftp/package.mk
  packages/addons/addon-depends/network-tools-depends/lftp/patches/lftp-0001-link-readline-with-termcap.patch
  packages/addons/addon-depends/network-tools-depends/rar2fs/package.mk
  packages/addons/tools/network-tools/changelog.txt
  packages/addons/tools/network-tools/package.mk
Labels: ADDONS, LE 10.0, PACKAGE, UPDATE

#5395 multimedia-tools: update addon to 115
  packages/addons/addon-depends/multimedia-tools-depends/depends/libmediainfo/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/depends/libzen/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/mediainfo/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/mpg123/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/mpv-drmprime/package.mk
  packages/addons/addon-depends/multimedia-tools-depends/squeezelite/package.mk
  packages/addons/tools/multimedia-tools/changelog.txt
  packages/addons/tools/multimedia-tools/package.mk
Labels: ADDONS, LE 10.0, PACKAGE, UPDATE

#5393 system-tools: update addon to 122
  packages/addons/addon-depends/system-tools-depends/bottom/package.mk
  packages/addons/addon-depends/system-tools-depends/depends/oniguruma/package.mk
  packages/addons/addon-depends/system-tools-depends/file/package.mk
  packages/addons/addon-depends/system-tools-depends/mc/package.mk
  packages/addons/addon-depends/system-tools-depends/mc/patches/mc-revert-wchar.patch
  packages/addons/addon-depends/system-tools-depends/mtpfs/package.mk
  packages/addons/addon-depends/system-tools-depends/stress-ng/package.mk
  packages/addons/addon-depends/system-tools-depends/stress-ng/patches/fix-parallel-build.patch
  packages/addons/addon-depends/system-tools-depends/unrar/package.mk
  packages/addons/addon-depends/system-tools-depends/vim/package.mk
  packages/addons/tools/system-tools/changelog.txt
  packages/addons/tools/system-tools/package.mk
Labels: ADDONS, LE 10.0, PACKAGE, UPDATE

#5396 busybox: kernel-overlays-setup: log depmod to /dev/kmsg
  packages/sysutils/busybox/scripts/kernel-overlays-setup
Labels: BUGFIX, LE 10.0

#5399 prep for 9.2.7 widevine release
  packages/mediacenter/LibreELEC-settings/package.mk
  packages/mediacenter/kodi/scripts/kodi-config
Labels: LE 9.2

#5401 Allwinner: linux: enable BT on Tanix TX6 and add wifi node for rtl8822cs (rtw88)
  projects/Allwinner/devices/H6/patches/linux/0020-arm64-dts-allwinner-h6-tanix-tx6-add-bt-enable-rtw88.patch
Labels: ALLWINNER, HARDWARE, LE 10.0

#5403 Kodi: Remove "disable addon dialog at startup" for LibreELEC
  packages/mediacenter/kodi/patches/kodi-100.31.le-addons-no-startupenable.patch
Labels: BUGFIX, LE 10.0

#5369 samba: update to 4.13.9
  packages/network/samba/package.mk
Labels: LE 10.0, PACKAGE, UPDATE

#5405 systemd: fix systemd-machine-id-setup for v247 special case
  packages/sysutils/systemd/scripts/systemd-machine-id-setup
  packages/sysutils/systemd/system.d/machine-id.service
Labels: BUGFIX, LE 10.0

#5400 Rockchip: RK3399pro: add initial support for “Radxa ROCK Pi N10”
  projects/Rockchip/README.md
  projects/Rockchip/bootloader/release
  projects/Rockchip/devices/RK3399/README.md
  projects/Rockchip/patches/linux/default/linux-0030-regulator-from-list.patch
  projects/Rockchip/patches/linux/default/linux-0040-rockchip-dts.patch
  scripts/uboot_helper
Labels: HARDWARE, ROCKCHIP

#5402 scripts/extract: add option 'PKG_TAR_STRIP_COMPONENTS'
  packages/readme.md
  scripts/extract
Labels: BUGFIX, BUILDSYSTEM, LE 10.0

#5389 [Allwinner,Generic,Rockchip] linux: Update to 5.10.41
  packages/linux/package.mk
  projects/Allwinner/patches/linux/0057-media-cedrus-Fix-HEVC-status-macros.patch
  projects/Allwinner/patches/linux/0063-media-v4l2-ctrls.c-fix-race-condition-in-hdl-request.patch
  projects/Allwinner/patches/linux/0064-media-v4l2-ctrls-fix-reference-to-freed-memory.patch
  projects/Rockchip/patches/linux/default/linux-0021-drm-from-list.patch
Labels: ALLWINNER, GENERIC, KERNEL, LE 10.0, ROCKCHIP, UPDATE

#5408 documentation: update Freenode references to Libera.Chat
  CONTRIBUTING.md
  README.md
Labels: DOCUMENTATION, LE 9.2

#5409 documentation: update Freenode references to Libera.Chat
  CONTRIBUTING.md
  README.md
Labels: DOCUMENTATION, LE 10.0
